In [1]:
from calendar import monthrange
from datetime import datetime
import pandas as pd
from pandas.api.types import CategoricalDtype
from io import BytesIO
import os
import json

import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

# Load locale custome modules
import sys
sys.path.append(os.path.abspath("../tools"))
from CloudIO.AzStorageClient import AzStorageClient
from edahelpers import *

pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)

In [3]:
root_dir =  os.path.abspath(os.getcwd()+"..\\..\\..\\..\\")
print("root:" + root_dir)
tmp_dir = root_dir + "\\.tmp\\"
data_dir = root_dir + "\\data\\"
cred_dir = root_dir + "\\.cred"
az_cred_file = cred_dir + '\\azblobcred.json'

# DEFINE TARGET BLOB/DATA
container = "gold-samples-data"
# blob_name = "gold_samples_full_data.parquet"
blob_name = "gold_samples_trim_data_0206.parquet" # Advisor suggested features only

root:C:\Users\mchau\Documents\co2-flux-hourly-gpp-modeling

# Download parquet data from Azure Storage Blob

In [4]:
# Download the parquet file
# ref: https://stackoverflow.com/a/68940709
azStorageClient = AzStorageClient(az_cred_file)
file_stream = azStorageClient.downloadBlob2Stream(container, blob_name)
data_df = pd.read_parquet(file_stream, engine='pyarrow')
print(f"data size: {data_df.shape}")
data_df.head()

data size: (1755923, 38)

,TA_ERA,SW_IN_ERA,LW_IN_ERA,VPD_ERA,P_ERA,PA_ERA,NETRAD,PPFD_IN,GPP_NT_VUT_REF,datetime,year,month,day,hour,date,EVI,NDVI,NIRv,b1,b2,b3,b4,b5,b6,b7,IGBP,koppen,minute,site_id,elevation,lat,long,koppen_sub,koppen_main,koppen_name,koppen_main_name,c3c4,c4_percent
0,16.848,18.478,336.152,3.049,0.0,97.965,-27.270,12.08,-0.437716,2000-07-26 05:30:00,2000,7,26,5,2000-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EBF,Temperate,30,FR-Pue,270.0,43.7413,3.5957,8,3,Csa,Temperate,C3,6.59
1,16.932,65.997,336.152,3.134,0.0,97.981,-16.690,74.61,0.879290,2000-07-26 06:00:00,2000,7,26,6,2000-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EBF,Temperate,0,FR-Pue,270.0,43.7413,3.5957,8,3,Csa,Temperate,C3,6.59
2,17.016,114.551,336.152,3.220,0.0,97.996,27.455,88.21,5.448740,2000-07-26 06:30:00,2000,7,26,6,2000-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EBF,Temperate,30,FR-Pue,270.0,43.7413,3.5957,8,3,Csa,Temperate,C3,6.59
3,17.100,252.095,339.113,3.305,0.0,98.012,84.205,274.01,6.434920,2000-07-26 07:00:00,2000,7,26,7,2000-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EBF,Temperate,0,FR-Pue,270.0,43.7413,3.5957,8,3,Csa,Temperate,C3,6.59
4,18.055,326.385,339.113,5.097,0.0,98.029,146.205,387.91,5.707650,2000-07-26 07:30:00,2000,7,26,7,2000-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EBF,Temperate,30,FR-Pue,270.0,43.7413,3.5957,8,3,Csa,Temperate,C3,6.59

In [5]:
# Optional: Save it to local
data_df.to_parquet(tmp_dir + blob_name)

# Read from local parquet file
# data_df = pd.read_parquet(tmp_dir + blob_name')